In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris


In [25]:
iris=load_iris()

In [26]:
#1.logistic regression
log=cross_val_score(LogisticRegression(),iris.data,iris.target)
log

C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [27]:
np.average(log)

0.9733333333333334

In [28]:
#2 decision tree
de=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
de

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [29]:
np.average(de)

0.9600000000000002

In [30]:
#3:svm
s=cross_val_score(SVC(),iris.data,iris.target)
s

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [31]:
np.average(s)

0.9666666666666666

In [32]:
#4.random_forest
ra=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
ra

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [33]:
np.average(ra)

0.9666666666666668

# The model with best performance is LogisticRegreesion:0.9733333333333334
